# ç½‘ç«™æ ‡é¢˜
logo_title: æ±ªé’¦çš„åšå®¢
# åˆå§‹åŒ–é£æ ¼ black/light
style: black

#SEOä¼˜åŒ–

## ç½‘ç«™æè¿°
description: ä½ å¥½ è¿™é‡Œæ˜¯æ±ªé’¦

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: Blog

# é¦–é¡µURL
link: #TODO

#æ ‡è¯­:
words: AI ğŸ¤–ï¸ Code ğŸ§‘â€ğŸ’» Life ğŸŒˆ

# ä½ çš„æ˜µç§°
author: WangQin
# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰
gender: /img/head.png #/img/female.png

favicon: /img/favicon.ico

# èœå•æ é…ç½®
menu:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://liuxunzhuo.tech
  GitHubğŸ’: https://github.com/QinMou000

# åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
# è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz

highlight:
  enable: true